### ISSUE TITLE
gender vs pronoun

### ISSUE THREAD

**Issue by suisea** [emdaniels/character-swap#1]
hi, as a trans person i'd like to say that pronoun doesn't necessarily correlate with gender, so i'd love if you were open to switching your language wrt that bit. switching pronouns =/= switching genders. i'd have just done a pull request but kind of wanted to explain my reasoning first.

also feature request for this to expand to "they" pronouns! ... haha, i should write that myself probably >.>

**Comment by emdaniels** [comment]
Thank you for taking the time to request this change and make the project better! I am definitely open to switching pronoun to whatever best describes what is being switched. Originally I had it as sexes but I thought that didn't correlate well either. What would you suggest? I'm also going to work on making a neutral version of the story as well as some bug fixes. Do you have recommendations for names or words to represent what's in the story?

**Comment by suisea** [comment]
Oh I meant like, rather than saying a "male" version of the story or saying "female pronouns" or whatever, you could say "he pronoun version" or "he/masculine gendered" (the latter, masculine gendered, is still kinda iffy/binary, but...) and instead of saying "he" and "she" are "male" or "female" pronouns, just refer to them as "he pronouns," etc. Does that make sense?

Or I could submit a pull request for the readme and edit it and you can see what I mean? :)

**Comment by emdaniels** [comment]
@suisea I've just updated a bunch of stuff- check it out and let me know what you think!

**Comment by suisea** [comment]
that's a lot better, thank you! :)
